default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: development_sample_app

test:
  <<: *default
  database: test_sample_app

production:
  <<: *default
  database: production_sample_app